version: '3'
services:
    db:
        build:
            context: .
            dockerfile: Dockerfile-db
        ports:
            - '3306:3306'
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASS}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
        network_mode: 'host'
    api:
        build:
            context: .
            dockerfile: Dockerfile-api
        depends_on:
            - 'db'
        ports:
            - 3000:3000
        network_mode: 'host'