version: '3'
services:
    db:
        image: tobi312/rpi-mariadb:10.3
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
            MYSQL_USER: '${MYSQL_USER}'
            MYSQL_PASSWORD: '${MYSQL_PASS}'
            MYSQL_DATABASE: '${MYSQL_DATABASE}'
        ports:
            - '3306:3306'
        restart: unless-stopped
        network_mode: 'host'
    api:
        build: .
        depends_on:
            - 'db'
        ports:
            - 3000:3000
        restart: unless-stopped
        network_mode: 'host'