version: '3'
services:
    db:
        image: "mysql:8"
        ports:
            - "3306:3306"
        volumes:
            - ./docker:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            MYSQL_DATABASE: "chaveiro"
    app:
        image: "phpmyadmin/phpmyadmin:latest"
        links:
            - "db"
        ports:
            - "5000:80"
        environment:
            - PMA_ARBITRARY=1