version: '3'
services:
    db:
        image: "mysql:5.7"
        ports:
            - "3306:3306"
        volumes:
            - ./docker:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASS}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
    app:
        image: "phpmyadmin/phpmyadmin:latest"
        links:
            - "db"
        ports:
            - "5000:80"
        environment:
            - PMA_ARBITRARY=1